apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watmarker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brandoyts/watmarker-gitops.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
