apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web-app
          env:
            - name: API_BASE_URL
              value: http://api-gateway:8080
