apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: web-app
          env:
            - name: API_BASE_URL
              value: http://api-gateway.api-gateway-staging.svc.cluster.local:8080
