apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark
spec:
  template:
    spec:
      containers:
        - name: watermark
          env:
            - name: APP_ENV
              value: staging
            - name: APP_PORT
              value: "6000"
            - name: AWS_REGION
              value: us-east-1
            - name: LEAPCELL_BASE_ENDPOINT
              value: https://objstorage.leapcell.io
            - name: LEAPCELL_CDN
              value: https://1xg7ah.leapcellobj.com/tink-image-storage-dxog-j3gg-xs5apkqa
            - name: AWS_ACCESS_KEY_ID
              value: 5fa3583c7c184021a3dde3d81499abed
            - name: AWS_SECRET_ACCESS_KEY
              value: c053182767882c294959be5ad5eabadaed762cf0855697dc70f98e6db8a03871
            - name: AWS_BUCKET
              value: tink-image-storage-dxog-j3gg-xs5apkqa
