apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark
spec:
  template:
    spec:
      containers:
        - name: watermark
          env:
            - name: APP_ENV
              value: production
            - name: APP_PORT
              value: 6000
