apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - environment: staging
                  url: https://kubernetes.default.svc
                - environment: production
                  url: https://kubernetes.default.svc
          - git:
              repoURL: https://github.com/brandoyts/watmarker-gitops.git
              revision: HEAD
              directories:
                - path: kubernetes/application/*/environment/{{environment}}
  template:
    metadata:
      name: "{{index .path.segments 2}}-{{index .path.segments 4}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/brandoyts/watmarker-gitops.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: "{{url}}"
        namespace: "{{index .path.segments 4}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
