apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: staging
            url: https://kubernetes.default.svc
            namespace: ingress-nginx
  template:
    metadata:
      name: ingress
    spec:
      project: default
      sources:
        - repoURL: https://github.com/brandoyts/watmarker-gitops.git
          targetRevision: HEAD
          path: kubernetes/infrastructure/ingress/environment/{{environment}}
        - repoURL: https://kubernetes.github.io/ingress-nginx
          targetRevision: 4.13.3
          chart: ingress-nginx
      destination:
        server: "{{url}}"
        namespace: "{{environment}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
