apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark
spec:
  template:
    spec:
      containers:
        env:
          - name: APP_ENV
            value: staging
          - name: APP_PORT
            value: 6000
